image:
 - Visual Studio 2017

clone_folder: c:\projects\source

install:
  - set QTDIR=C:\Qt\5.9.1\msvc2017_64
  

environment:
  BOOST_ROOT: C:\Libraries\boost_1_61_0


build_script:
  - qmake -r "BOOST_ROOT=C:\Libraries\boost_1_61_0"